# Generated by Django 4.2.4 on 2023-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date_apply', models.DateField(auto_now_add=True)),
                ('date_published', models.DateField()),
                ('contacted', models.BooleanField(default=False)),
                ('interviewed', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'Remoto'), (1, 'Hibrido'), (2, 'Presencial')], default=0)),
                ('salary', models.CharField(max_length=40)),
            ],
        ),
    ]
